### ISSUE TITLE
SupportedFileFormats are rendered incorrectly for v0.3.x input

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-vue-components#10]
The sorting mechanism (whose output is then rendered) uses the user-supplied (i.e. non-migrated) `formats` prop, not the component-generated (i.e. migrated) `outputFormats` data.

![grafik](https://user-images.githubusercontent.com/17781682/63336219-0eca3680-c33f-11e9-96c0-4f1b1cbe7a3c.png)

I.e. these lines:

https://github.com/Open-EO/openeo-vue-components/blob/8f9f6a3586cef9a798339900320a2c6ba385e894/components/SupportedFileFormats.vue#L36-L37

should be changed to:

```
 			if (this.outputFormats && typeof this.outputFormats === 'object') { 
				return Object.keys(this.outputFormats).sort(Utils.compareStringCaseInsensitive); 
```

**Comment by m-mohr** [comment]
Fixed and released as 0.4.1.
