### ISSUE TITLE
Tab is not closable

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-vue-components#14]
During the workshop, I saw the situation on a participant's laptop that tabs were not closable -- i.e. when you clicked on the X symbol, nothing happened. No error was displayed in a toast. I checked his console, but no errors were being logged there either.

No idea what may have caused it, i.e. no idea how to reproduce, but I still wanted to mention it.

**Comment by m-mohr** [comment]
There's no special handling in the Web Editor, therefore the issue must be in vue-components. Moved it. Nevertheless, I wasn't able to reproduce it yet.
