### ISSUE TITLE
FeatureList should be updated

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-vue-components#16]
The categories 'Authenticate with HTTP Basic' and 'Authenticate with OpenID Connect' should no longer be their own categories because most users don't care about that (probably don't even know what it is). Suggestion was to move it into the 'Basic functionalities' category. However, so far not all backends support both methods - that has to be dealt with.

'Notifications and monitoring' should be removed as it is no longer part of the API. (Or move it to legacyFeatures?)

**Comment by m-mohr** [comment]
Released as 1.0.0-beta.1
