### ISSUE TITLE
Tabs: spaceLimited not applied uniformly

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-vue-components#21]
I have discovered a problem with the tabs at the Hub. On the initial page load, the tabs look like this:

![grafik](https://user-images.githubusercontent.com/17781682/78023255-a3c1f300-7356-11ea-9a0d-c583cc1d6ef2.png)

But after changing the tab, the sizes of all pills change:

![grafik](https://user-images.githubusercontent.com/17781682/78023592-3498ce80-7357-11ea-9c41-cca9959d556c.png)

I found out this happens because the `spaceLimited` class is set initially, which applies `min-width: auto`. But after changing to a different tab, this class disappears, causing the resize.

I had a brief look into the code and assume this has probably to do with the `adjustSizes` function?

**Comment by m-mohr** [comment]
What do you mean by "after changing the tab"?

**Comment by christophfriedrich** [comment]
I meanswitching between tabs. What I did between the first and the second screenshot was: Clicking on "v0.4.1".

**Comment by m-mohr** [comment]
I guess this has something to do with that adjustSizes is called before this.$refs.tabsHeader is defined. I guess that happens because it's in a collapsible area in the Hub, because I've never seen this behavior before.

**Comment by m-mohr** [comment]
Is the collapsible doing a v-if or v-show?

**Comment by christophfriedrich** [comment]
It's a `v-show`: https://github.com/Open-EO/openeo-hub/blob/c18f32eed724305ff7b7dc7bd93c300321846514/src/components/BackendGroup.vue#L8

**Comment by m-mohr** [comment]
As discussed: The issue is that it's in a v-show block. The component is mounted, but can't get any bounding box from the tab area so can't calculate whether there's enough space. Workaround for v-show use cases is to call adjustSizes() manually after expanding or set the CSS yourself to the desired default behavior.
