### ISSUE TITLE
Bounding box that involves 180 isn't displayed

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-vue-components#26]
Happens with e.g. collection `WWF/HydroSHEDS/30DIR` of GEE

Edit: Not on the currently deployed version of the Hub which still uses `1.0.0-beta.6`, so the bug is probably due to you trying to fix the anti-meridian issue?

Edit2: Also with `USGS/LIMA/MOSAIC`

**Comment by m-mohr** [comment]
The bounding box provided by GEE is invalid: 
It is [180,-67.3,-180,62], but must be [-180,-67.3,180,62]
