### ISSUE TITLE
Some collection descriptions are not rendered

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-vue-components#34]
Example: `MODIS/MOD09GA_006_NDVI` collection in GEE.

JSON of that collection's `description` property (extracted via Vue dev tools):
```
"\"<p> The Normalized Difference Vegetation Index is\\ngenerated from the Near-IR and Red bands of each scene as (NIR - Red) /\\n(NIR + Red), and ranges in value from -1.0 to 1.0. This product is generated from the MODIS/006/MOD09GA surface reflectance composites.</p>\""
```

Screenshot:
![grafik](https://user-images.githubusercontent.com/17781682/106275029-85a67700-6235-11eb-9dbb-80306a8a1ae2.png)

There's no error (or any other relevant output) in the console.

Happens both on the deployed version of the Hub as well as in my locally running version that is `npm link`ed to the `vue-components`'s `dev` branch. Other collections work, so it doesn't seem to be related to Open-EO/openeo-hub#87.

**Comment by m-mohr** [comment]
This is very likely due to the fact that it's inside a `<p>` HTML tag. HTML is not allowed for security reasons. Commonmark seems to strictly remove everything inside HTML tags. I don't think there's anything to fix here, except that GEE should better not output unnecessary HTML in Markdown.
