### ISSUE TITLE
Improve collection band rendering

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-vue-components#39]
My collection rendering shows bands twice, screenshots below for `connection.describe_collection('SENTINEL2_L1C_SENTINELHUB')`

The full table is nicer than the list, but shown later. Can the html component show only one list of bands? I know there's some underlying complexity because of bands in STAC, but would be better if we can hide that from the user. 

![image](https://user-images.githubusercontent.com/5937096/113672459-1bd49e80-96b8-11eb-9488-fe9608c53d84.png)

![image](https://user-images.githubusercontent.com/5937096/113672512-2d1dab00-96b8-11eb-9ba7-5bd80265653a.png)

**Comment by m-mohr** [comment]
There's a difference with spectral bands and bands in a file. The spectral bands (eo:bands) should not include CLP, CLM, sun..., view... bands, but those of course are labels in the data cube. STAC will allow raster:bands soon.

So it's not as easy as just replace one with the other as it may be incomplete.

**Comment by m-mohr** [comment]
The list of bands labels is no comma separated and consumes less space so that the eo:bands jump up a bit. Also, you can click the "bands" link, which will make the browser jump down to the spectral bands. I think that's the closest we'll get with the many use cases we have in mind.
