### ISSUE TITLE
File formats shouldn't be upper-cased automatically

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-vue-components#4]
This is the file format list of the R demo server:

> ![image](https://user-images.githubusercontent.com/17781682/54126081-00c6d000-4407-11e9-8d8c-a468f9593af2.png)

I think it wouldn't make the list more readable when *each* entry is printed entirely in upper case. Therefore, while it was a well-intended idea, `toUpperCase()` shouldn't be called automatically for each and every file format name:

https://github.com/Open-EO/openeo-vue-components/blob/f4b94d6ef9dacc180512c33ab146be79cc330abb/components/SupportedFileFormats.vue#L3

A compromise could be to check whether the name consists only of characters from one case (i.e. satisfies either `/^[a-z]+$/` or `/^[A-Z]+$/`) and if yes convert to upper case, since uppercasing an all-lower-case name is indeed an improvement.

The same issue possibly applies to supported service types (but I don't have such an impressive example for that):

https://github.com/Open-EO/openeo-vue-components/blob/f4b94d6ef9dacc180512c33ab146be79cc330abb/components/SupportedServiceTypes.vue#L3

**Comment by m-mohr** [comment]
They are now rendered as in the responses.

**Comment by m-mohr** [comment]
Implemented as suggested.
