### ISSUE TITLE
Make basemap tile layer configurable

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-vue-components#43]
The base map tile layer is currently using OSM data, which has a strict scope of usage. Commercial services using (e.g. Platform) may need to use a different tile service, e.g. Maptiler, Carto, Mapbox, Google. To make this easier to change, add an option to easily change the base map service.

**Comment by clausmichele** [comment]
+1 on this. It would be nice to have a satellite RGB layer too, but I don't know if there is an open source one.

**Comment by m-mohr** [comment]
@clausmichele I don't think there's one. The default will likely always be OSM, but in Platform, we may integrate a paid version at some point.

**Comment by m-mohr** [comment]
This is now possible.

@clausmichele You could register for a Mapbox free tier account and they have satellite tiles if you want to add them to the EURAC Web Editor or so...

**Comment by clausmichele** [comment]
Thanks! I'll look into that when I find some time.

**Comment by clausmichele** [comment]
@m-mohr I'm currently using the Platform Editor and in my opinion the mapbox layer has now too little details. Is it possible to customize it? From OSM I was able to distinguish much better the area I wanted to look at: 
![image](https://user-images.githubusercontent.com/31700619/146335260-55254f91-2d30-46d7-aaa6-cdb72fb34d08.png)

If not, I'll use the back-end specific editor.

**Comment by m-mohr** [comment]
We can use any other Mapbox style: Which one do you think is preferable?
https://docs.mapbox.com/api/maps/styles/

**Comment by clausmichele** [comment]
I would say that Streets is already more detailed. A satellite RGB would also be nice to have.
I don't know if it would make sense to have the possibility to select one of two layers, since there's already a "layers" button in the viewer:
1. mapbox streets
2. mapbox satellite
Anyway, we can discuss with the others asking if it's something we need or not.

**Comment by m-mohr** [comment]
Not possible for the Vue components, but definitely possible for the Web Editor - and you can have them ALL (except OSM):

![image](https://user-images.githubusercontent.com/8262166/146365757-649fad89-6fa7-4f21-8ca6-5375be49c119.png)

**Comment by m-mohr** [comment]
@clausmichele The Platform Editor now offers you a variety of 5 different base maps :-)

**Comment by clausmichele** [comment]
Great!
