### ISSUE TITLE
Preview image is displayed within map area

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-vue-components#44]
When the `Collection` component in the Hub is provided with the "full" information including previews, the preview image is displayed within the map area:

> ![grafik](https://user-images.githubusercontent.com/17781682/121050117-9a34e600-c7b8-11eb-9561-0a265e622639.png)

When zooming in, the image gets more and more hidden:

> ![grafik](https://user-images.githubusercontent.com/17781682/121050292-bd5f9580-c7b8-11eb-8411-48058898a724.png)

until it's fully covered by the map and no longer visible at all:

> ![grafik](https://user-images.githubusercontent.com/17781682/121050656-0d3e5c80-c7b9-11eb-9d4c-b6d8e2821f5a.png)

**Comment by christophfriedrich** [comment]
Initially I thought this is due to conflicting CSS, but maybe it's more because of _missing_ CSS? The zoom controls don't look like they usually do and the attribution label looks a bit unstyled too.

For reference, this is what such an extent map looked like in an older version:

> ![grafik](https://user-images.githubusercontent.com/17781682/121051141-7d4ce280-c7b9-11eb-9848-7b5438fb87e2.png)

**Comment by m-mohr** [comment]
I can't reproduce this.

It may not be the missing CSS though as removing the CSS entirely, makes it look even worse (tiles randomly ordered, no buttons).

Does this happen with AND without the "updating" of the full collection metadata? May that be the issue?

**Comment by m-mohr** [comment]
For whatever reason both the Vue $refs and the document.getElementById calls to the map element were pointing to the preview div when updating the data from externally. The map HTML was then inserted into the preview div. This seems to be a race condition, an issue with Vue's reactivity or something similar. The only workaround we found is to replace the v-if for the preview element with v-show. Still a pretty obscure issue...
