### ISSUE TITLE
Issue with temporal extent "Fatal error: invalid duration string"

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-vue-components#45]
There are some issues with the temporal extent, maybe this is a bug coming from the latest fix supporting collections with no temporal extent?

For example, this collection seems fine to me (except some fields we have to update as suggested): https://openeo.eurac.edu/collections/ADO_VCI_MODIS_231m_3035
But in the web editor it complains about an _invalid duration string_.
![image](https://user-images.githubusercontent.com/31700619/121301945-382fca00-c8f9-11eb-8e92-50dc77420919.png)

This issue is not present using the Web Editor version 0.6

**Comment by m-mohr** [comment]
Fixed in Vue components, will be part of the next Web Editor release.

**Comment by m-mohr** [comment]
The fix is available in Web Editor v0.7.5 (available from dev branch) and online @clausmichele
