### ISSUE TITLE
Move endpoints-to-functionality map

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-vue-components#5]
See Open-EO/openeo-hub#15

I think this constant:

https://github.com/Open-EO/openeo-vue-components/blob/bfafe30712e36bc94ad695c944405f75e86ac4e2/components/SupportedFeatures.vue#L12

should be moved to the `openeo-js-commons` repo.

**Comment by m-mohr** [comment]
Implemented with commit d6e0dbb65d97457d4a4ec1d7d13270dfd52a841b. It now has a whole class with different methods to analyze the features. I hope it caters all your needs. Released as v0.3.2.
