### ISSUE TITLE
extrema return type: any?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-vue-components#70]
(spin off from Open-EO/openeo-processes#277 )

https://processes.openeo.org/#extrema  describes return type of `extrema` as `any`:
```
extrema(array<number|null> data, ?boolean ignore_nodata = true) : any
```

should be `array` I think

**Comment by soxofaan** [comment]
can't you just use the way it's done for the `data` argument:
```
data
An array of numbers.
Data type:  array<number|null>
```

I don't think it's a big issue to relax `array<number> | array<null>`  to `array<number|null>`

**Comment by m-mohr** [comment]
I looked for a bug in a completely different spot than expected. 😅
Anyway, extrema (and all other multi-type return values) are fixed now.
extrema will now result in `extrema(array<number|null> data, ?boolean ignore_nodata = true) : array`
