### ISSUE TITLE
Space-efficiency of asset listing

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-vue-components#77]
I you have a batch job with multiple result assets, the listing (e.g. in jupyter notebook) wastes quite a lot of vertical space (lot of margins, short lines), while there is plenty of horizontal space.

![Screenshot from 2022-02-03 11-58-53](https://user-images.githubusercontent.com/44946/152330401-671396d9-ba97-438d-b054-9456ba729302.png)

Reorganizing the structure from vertical to horizontal is probably not trivial, but I would at least reduce the generous margins/paddings.

**Comment by m-mohr** [comment]
Space efficiency improved
