### ISSUE TITLE
Hard to copy collection id from collection overview

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-vue-components#81]
When visiting a collection listing like on https://docs.openeo.cloud/data-collections/ , it's hard to copy the actual collection id (so that I can paste it in my script/notebook). Because the collection id it is clickable (to toggle the collection's description/metadata), it's hard to select it for copying:  double clicking doesn't work and select by dragging feels weird because my mouse pointer changed to `cursor: pointer;`  style

Not sure what would be easiest/best:
Could we add a small button with "copy this collection id to clipboard" functionality, 
or add a field on the collection overview that explicitly states "collection id" and some kind of text widget that makes it easy/obvious to copy?

**Comment by m-mohr** [comment]
The same issue applies for all lists basically. 
I'll check whether a copy button will work, probably the most annoying bit is to get an icon for it that can be used in the web components.

**Comment by m-mohr** [comment]
I've added an experimental clipboard icon that shows after hovering the title which you can use to copy the identifier.
This likely only works in modern browsers and may not show icons for all fonts. Let's see how it works.

**Comment by soxofaan** [comment]
thanks, seems to work fine for me
