### ISSUE TITLE
Display only 2 decimales in the cost estimate results

### ISSUE THREAD

**Issue by dthiex** [Open-EO/openeo-vue-components#85]
In order to avoid confusion with the displayed cost estimate I think it would make sense to only display 2 decimals (FF takes the separator from the system settings for the costs). 2 decimals is still more then precise enough. 

![cost_estimate_batch_job](https://user-images.githubusercontent.com/60705209/181017729-95855bf9-bffe-432b-bab0-94c15613e70a.png)

Additional I think the same separator should be used for costs and file size.

**Comment by m-mohr** [comment]
Actually, this is not a Web Editor issue but a Vue Component issue. Moving it...

**Comment by m-mohr** [comment]
I can't change the cost representation in a good way as this originates from JavaScripts toLocaleString implementation, which uses three fraction digits when no valid currency is set (and processing units are obviously not considered a valid currency ;-) ).  I could turn off the thousand separator, but not sure whether that's helpful...

**Comment by dthiex** [comment]
>  I could turn off the thousand separator, but not sure whether that's helpful...

I think for a bit bigger jobs that use >1000 PUs it would be helpful. Can't you set something maximumFractionDigits = 2?

**Comment by m-mohr** [comment]
I can, but then I'm forcefully overriding the currency defaults, which you still want to be considered.

Nevertheless, the file size is now aligned and shows "15,2 MB" instead. That should help a bit...

**Comment by m-mohr** [comment]
Okay, I just checked ISO-4217 and the codes are all 3 chars. So I can set the maximumFractionDigits to 2 for all currencies that are not 3 chars long :-)

**Comment by m-mohr** [comment]
Fixed, will need some time until it's landing in the Web Editor though...
