### ISSUE TITLE
Logs widget: support filtering on "code" field of logs

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-vue-components#87]
see https://discuss.eodc.eu/t/printing-or-logging-from-udf/421/5 for context (initial support for logging from UDFs)

the `inspect` process promotes usage of `code="User"`  field for easier identifying user generated log entries, but the current logs widget has very limited support for thus "Code" field: it just renders it as a field alongside "Data" and "ID":
![Screenshot from 2022-09-21 17-22-40](https://user-images.githubusercontent.com/44946/191546945-729238e0-50e9-4449-bd63-eb45dce92517.png)

some suggestions/ideas:
- render code more as a tag like  the level on the right
- allow filtering on code (now only filtering on message content is supported if I understand correctly)
- make the "ID" field less prominent or even hidden by default (I don't think it has currently any practical use)

**Comment by m-mohr** [comment]
Filtering on code is allowed, simply type "User" in the search box. 

The ID field might be useful for support requests and as such it should be visible as well.

Whenever we have some more implementations of the inspect process, I'll look into how I can improve the handling of it better in the components. Always showing the code as badge might not be ideal as they can be very long - I don't have checked it, but I think we have something like "DimenionsLabelConflictException" or so...

**Comment by soxofaan** [comment]
> Filtering on code is allowed, simply type "User" in the search box. If it doesn't work yet, it's a bug.

indeed, but in the VITO backend case a lot of messages match on "user" too because the the working dir of batch jobs contains a "/usercache/" part, so you get a lot of "false" positive hits:
![Screenshot from 2022-09-22 09-13-41](https://user-images.githubusercontent.com/44946/191682282-0e9a6c8b-ab83-48e8-8da9-52bdedd62ab3.png)


> Whenever we have some more implementations of the inspect process, I'll look into how I can improve the handling of it better in the components.

Yes, sure, not urgent at the moment. We just recently started experimenting with  `inspect` from UDFs  and still have to figure some things out too

**Comment by m-mohr** [comment]
I think I'll just provide an additional mutli-select right to the search box where you'll be able to select the fields to search on.

**Comment by soxofaan** [comment]
looks great, thanks
