### ISSUE TITLE
Visualizing process tree in dark theme notebook

### ISSUE THREAD

**Issue by Pratichhya** [Open-EO/openeo-vue-components#89]
When using dark theme notebook, parameters name are not well displayed.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/39898768/204307366-f8a51eee-443c-43e0-970e-8c81111c9760.png)

**Comment by m-mohr** [comment]
Dark theme is not supported right now as I can't detect it from the Vue components. Unfortunately, I'm not sure how I could fix this...

**Comment by christophfriedrich** [comment]
For reference: That was done in commit 70100245bf8d284aaf9f3a53cf7ac9c62e7cd0ac
