### ISSUE TITLE
Feature request: Provide option to sort file formats and service types

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-vue-components#9]
In the Hub, I used to sort the file formats and service types alphabetically so the (possibly long -- cf. R backend) lists are easier to read. This is not possible when passing the data as object, so if we want to continue this feature (which I find handy) we have to do the sorting in the components themselves.

**Comment by m-mohr** [comment]
Good idea, will be scheduled for implementation.

**Comment by m-mohr** [comment]
Implemented, will be released as part of v0.3.10.
