### ISSUE TITLE
logs widget: stuck with only error level logs

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-vue-components#93]
![image](https://github.com/Open-EO/openeo-vue-components/assets/44946/7a959571-43e4-45b5-bb8d-1a25541d78d3)

I can disable logs level (clicking the "x") and re-enable log levels again (through the dropdown).
But once "error" is the only remaining log level I can not enable any other level anymore (the drop down widget does not appear anymore)

**Comment by soxofaan** [comment]
context info: working with latest master of openeo client in jupyterlab 4.0.2 in Firefox  113.0.2

Screenshot above indeed indeed does not show the issue, just the state before.

Attempt to illustrate behavior with video (which now has slightly different behavior than in my original post):

[Screencast from 19-06-23 17:00:58.webm](https://github.com/Open-EO/openeo-vue-components/assets/44946/820eb03d-4172-413d-9d10-a781e3fad05b)

when only "error" is left: note how the drop down shrinks to only show DEBUG, and a slice of INFO
when only "warning" is left: ERROR is sliced off in the drop down

**Comment by m-mohr** [comment]
I think it should be solved with https://github.com/Open-EO/openeo-vue-components/commit/85286d392716b47d4531fadfd88863f801dfaa02 but as I still can't reproduce this myself, I guess we have to check with the next release.

**Comment by soxofaan** [comment]
is there a way to show version info about the active openeo vue components, e.g. in a jupyter notebook?

If possible we should hook that into `openeo.client_version()` in some way
![image](https://github.com/Open-EO/openeo-vue-components/assets/44946/16472e3a-3042-4413-b582-5409e482fe9e)

**Comment by m-mohr** [comment]
No, it should be the latest though.
